package com.lotus.gausscmp.compare.diff;

public enum DiffType {
    TABLE_MISSING_IN_TARGET, TABLE_EXTRA_IN_TARGET,
    COLUMN_MISSING_IN_TARGET, COLUMN_EXTRA_IN_TARGET, COLUMN_MISMATCH,
    CONSTRAINT_MISSING_IN_TARGET, CONSTRAINT_EXTRA_IN_TARGET, CONSTRAINT_MISMATCH,
    INDEX_MISSING_IN_TARGET, INDEX_EXTRA_IN_TARGET, INDEX_MISMATCH,
    TABLE_COMMENT_MISMATCH
}
